apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rendertron-deployment-hpa
spec:
  maxReplicas: 20 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rendertron-deployment
  targetCPUUtilizationPercentage: 20 # target CPU utilization
