apiVersion: v1
kind: Service 
metadata:
  name: rendertron-svc
spec:
  type: ClusterIP # ClusterIP, # NodePort, # LoadBalancer
  selector:
    app: rendertron
  ports: 
    - name: http
      port: 3000 # Service Port
      targetPort: 3000 # Container Port
